### ISSUE TITLE
Flush RPC: FlushResponseError.Reason when neither election id nor override are specified

### ISSUE THREAD

**Issue by nandanarista** [openconfig/gribi#23]
Today in the FlushRequest, if `election` doesn't specify a `id` nor `override` in single primary mode, there's no Reason enum for this error. Does it make sense to add a specific enum like NO_ELECTION_ID_OR_OVERRIDE to ModifyResponseError.Reason ?

**Comment by robshakir** [comment]
This sounds reasonable to me -- and covers some of the same concerns as #24.

**Comment by robshakir** [comment]
I suggest we also specify in the proto what the canonical code that is used is.  Particularly, whilst implementing this, I thought:

* when ID is specified but is not the current master `FAILED_PRECONDITION` (note that we don't have an analogue here in `Modify` because there this condition is not a fatal error).
* when the network instance is not found, `INVALID_ARGUMENT` (again, we don't have a an analogue here for the same reason as above in `Modify`)
